# Robot Framework will automatically convert these to ${URL}, ${BROWSER}, etc.
URL = "http://localhost:5173/"
BROWSER = "Chrome"
TEXTFIELD_ID = "id:content"
AUTHOR_ID = "id:author"
WEBSITE_ID = "id:website"
CHECK_BUTTON = "id:analyze-button"
FAKE_CONFIDENCE_SELECTOR = "id:confidence-percentage"
RISK_LABEL = "xpath=//*[text()='Low Risk' or text()='Medium Risk' or text()='High Risk']"
FIRST_HISTORY_ITEM = "id:history-item-1"
SECOND_HISTORY_ITEM = "id:history-item-2"
FIRST_HISTORY_ITEM_BUTTON = "history-menu-button-1"
SECOND_HISTORY_ITEM_BUTTON = "history-menu-button-2"
CLEAR_HISTORY_BUTTON_SELECTOR = "id=clear-history-button"
HISTORY_EMPTY_TEXT = "No history yet"