name: Python CI (Windows)

on:
  push:
    branches:
      - main
      - Developing
      
  pull_request:
    branches:
      - main
      - Developing
      - feature/**
    paths:
      - .github/workflows/backend-ci.yml
      - Backend/**
      - TensorflowModel/**
      - requirements.txt

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r Backend/requirements-dev.txt
        shell: cmd

      - name: Run Linter (flake8)
        run: |
          flake8 .
        shell: cmd

      - name: Run Tests (pytest)
        run: |
          pytest --maxfail=1 --disable-warnings -q
        shell: cmd
