name: Python CI (Windows)

on:
  push:
    branches:
      - main
      - Developing
      
  pull_request:
    branches:
      - main
      - Developing
      - feature/**
    paths:
      - .github/workflows/backend-ci.yml
      - Backend/**

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: Backend/requirements*.txt

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
        shell: cmd
        working-directory: ./Backend

      - name: Run Linter (flake8)
        run: |
          flake8 .
        shell: cmd
        working-directory: ./Backend

      - name: Run Coverage (pytest with coverage)
        run: |
          coverage run --branch --source=. -m pytest --maxfail=1 --disable-warnings -q
        shell: cmd
        working-directory: ./Backend
      
      - name: Show Coverage Report
        run: |
          coverage report -m
        shell: cmd
        working-directory: ./Backend

      - name: Generate HTML Coverage Report
        run: |
          coverage html -d coverage_html_report
        shell: cmd
        working-directory: ./Backend

      - name: Upload Coverage Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: ./Backend/coverage_html_report
