name: Python CI (Windows)

on:
  push:
    branches:
      - main
      - Developing
      - "T*"  # Matches any branch that starts with "T"
  pull_request:
    branches:
      - main
      - Developing

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]  # Test with multiple Python versions

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if exist requirements.txt pip install -r requirements.txt
        shell: cmd

      - name: Run Linter (flake8)
        run: |
          pip install flake8
          flake8 .
        shell: cmd

      - name: Run Tests (pytest)
        run: |
          pip install pytest
          pytest
        shell: cmd