name: Run ESLint

on:
  pull_request:
    branches:
      - main
      - Developing
    paths:
      - 'frontend/**'

jobs:
  lint:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run ESLint
        working-directory: ./frontend
        run: npm run lint

  robot:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Dependencies
        working-directory: ./tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Drivers
        run: webdrivermanager firefox

      - name: Run Frontend
        working-directory: ./frontend
        run: npm run dev:pin

      - name: Front end tests
        run: robot .\tests\

